version: '3'
services:
  signalk-server:
    build: ./docker
    privileged: true
    volumes:
      - ./docker/config:/opt/signalk
      - ./packages/signalk-to-awsiotcore:/opt/signalk/node_modules/signalk-to-awsiotcore
    ports:
      - 3000:3000
      - 8375:8375
      - 10110:10110

